### ISSUE TITLE
The Installation of the package Crumple doesn't work...

### ISSUE THREAD

**Issue by Sophie-BFT** [aussieBIMguru/Crumple#1]
Hey,

Thanks for your package. Unfortunately I've a problem with its installation. Everything is installed but I can't see the Contents when I click on "show Contents" allthough I follow all the description and way to install your package.
Fyi, I use Revit 2019 and Dynamo 2.0.2 6661
Could you please help me to resolve my problem?

Thanks a lot
![200914_Issue](https://user-images.githubusercontent.com/71260411/93090916-bbd7c580-f69d-11ea-8484-fef08b609f4f.PNG)

Kind regards 

Sophie

**Comment by aussieBIMguru** [comment]
Hi Sophie, this package is developed for Dynamo 2.3 in Revit 2020 so I don't believe it will perform the same way in 2019. Based on the fact the Json data is reading itself as a package, I'm guessing you may have put the package contents in the directory instead of a subfolder.

See attached how it should look (ignore the synctoy file).

![folder1](https://user-images.githubusercontent.com/58870499/93549322-6573cb00-f9ac-11ea-914b-647aff48efe6.PNG)
![folder2](https://user-images.githubusercontent.com/58870499/93549326-673d8e80-f9ac-11ea-843d-cf7358d0018a.PNG)

**Comment by aussieBIMguru** [comment]
It's on package manager now, some other users were having similar issues.

**Comment by Sophie-BFT** [comment]
Hey Gavin!

Thanks a lot for your answers! I’ll try it and tell you if it works!

Have a nice Day

Sophie

Von: Gavin Crump <notifications@github.com>
Gesendet: Dienstag, 22. September 2020 11:31
An: aussieBIMguru/Crumple <Crumple@noreply.github.com>
Cc: Huriaux, Sophie <Sophie.Huriaux@bft-planung.de>; Author <author@noreply.github.com>
Betreff: Re: [aussieBIMguru/Crumple] The Installation of the package Crumple doesn't work... (#1)


It's on package manager now, some other users were having similar issues.
